all: kmeans rls ils ga

kmeans: kmeans.cpp
	g++ -std=c++11 kmeans.cpp -o kmeans

rls: rls.cpp
	g++ -std=c++11 rls.cpp -o rls

ils: ils.cpp
	g++ -std=c++11 ils.cpp -o ils

ga: ga.cpp
	g++ -std=c++11 ga.cpp -o ga

clean:
	rm -f kmeans rls ils ga
